import type { Item } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => {
  const placeholder = PlaceHolderImages.find(p => p.id === id);
  return placeholder || { imageUrl: 'https://picsum.photos/seed/default/600/400', imageHint: 'placeholder' };
};

export const items: Item[] = [
  {
    id: '1',
    title: 'Caja de Lápices de Colores',
    description: 'Caja de 24 lápices de colores Faber-Castell, sin usar. Perfecta para clases de arte.',
    category: 'Útiles',
    condition: 'Nuevo',
    gradeLevel: 'Primaria',
    imageUrl: getImage('item-1').imageUrl,
    imageHint: getImage('item-1').imageHint,
    postedBy: 'Ana G.',
    isReserved: false,
    status: 'Disponible',
  },
  {
    id: '2',
    title: 'Uniforme Escolar Talla 10',
    description: 'Pantalón y camisa de uniforme escolar. Talla 10. Buen estado, poco uso.',
    category: 'Uniformes',
    condition: 'Como nuevo',
    gradeLevel: 'Primaria',
    imageUrl: getImage('item-2').imageUrl,
    imageHint: getImage('item-2').imageHint,
    postedBy: 'Luis M.',
    isReserved: false,
    status: 'Disponible',
  },
  {
    id: '3',
    title: 'Libro de Matemáticas 1ro Secundaria',
    description: 'Libro de texto de Matemáticas para primer año de secundaria. Editorial Santillana. Forrado y en buen estado.',
    category: 'Libros',
    condition: 'Usado',
    gradeLevel: 'Secundaria',
    imageUrl: getImage('item-3').imageUrl,
    imageHint: getImage('item-3').imageHint,
    postedBy: 'Carla P.',
    isReserved: false,
    status: 'Disponible',
  },
  {
    id: '4',
    title: 'Mochila Juvenil',
    description: 'Mochila marca "CoolPack" con varios compartimentos. Ideal para secundaria o bachillerato. Cierres en perfecto estado.',
    category: 'Útiles',
    condition: 'Usado',
    gradeLevel: 'Secundaria',
    imageUrl: getImage('item-4').imageUrl,
    imageHint: getImage('item-4').imageHint,
    postedBy: 'Jorge F.',
    isReserved: true,
    reservedBy: 'test@test.com',
    status: 'Reservado',
  },
  {
    id: '5',
    title: 'Calculadora Científica Casio',
    description: 'Calculadora científica Casio fx-82MS. Funciona perfectamente, incluye tapa protectora.',
    category: 'Útiles',
    condition: 'Como nuevo',
    gradeLevel: 'Bachillerato',
    imageUrl: getImage('item-5').imageUrl,
    imageHint: getImage('item-5').imageHint,
    postedBy: 'Sofia R.',
    isReserved: false,
    status: 'Disponible',
  },
  {
    id: '6',
    title: 'Diccionario Español-Inglés',
    description: 'Diccionario bilingüe Larousse, edición de bolsillo. Muy útil para clases de idiomas.',
    category: 'Libros',
    condition: 'Usado',
    gradeLevel: 'Todos',
    imageUrl: getImage('item-6').imageUrl,
    imageHint: getImage('item-6').imageHint,
    postedBy: 'Miguel A.',
    isReserved: false,
    status: 'Disponible',
  },
  {
    id: '7',
    title: 'Paquete de Cuadernos',
    description: 'Paquete de 5 cuadernos de raya, 100 hojas cada uno. Completamente nuevos.',
    category: 'Útiles',
    condition: 'Nuevo',
    gradeLevel: 'Todos',
    imageUrl: getImage('item-7').imageUrl,
    imageHint: getImage('item-7').imageHint,
    postedBy: 'Laura V.',
    isReserved: false,
    status: 'Disponible',
  },
  {
    id: '8',
    title: 'Falda de Uniforme Talla 14',
    description: 'Falda tableada de uniforme escolar, color azul marino, talla 14. Excelente estado.',
    category: 'Uniformes',
    condition: 'Como nuevo',
    gradeLevel: 'Secundaria',
    imageUrl: getImage('item-8').imageUrl,
    imageHint: getImage('item-8').imageHint,
    postedBy: 'Daniela C.',
    isReserved: false,
    status: 'Disponible',
  },
];
